services:
  app:
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    # The following command can be uncommented during local development to ensure Composer dependencies are installed before starting supervisord.
    # command: ["sh", "-c", "composer install --no-interaction --no-ansi --no-scripts --prefer-dist || true && /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf"]
    ports:
      - "9000:9000"
    tty: true

  nginx:
    ports:
      - "8080:80"
