[unix_http_server]
file=/tmp/supervisor.sock
chmod=0770
chown=foto:foto

[supervisord]
nodaemon=true
user=foto
logfile=/dev/null
pidfile=/tmp/supervisord.pid
childlogdir=/tmp

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[program:php-fpm]
command=docker-php-entrypoint php-fpm
user=foto
autostart=true
autorestart=true
priority=10
stdout_logfile=/dev/fd/1
stderr_logfile=/dev/fd/2
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

[program:horizon]
command=/bin/bash -c "/usr/local/bin/wait-for-redis.sh php artisan horizon"
user=foto
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
priority=20
stdout_logfile=/dev/fd/1
stderr_logfile=/dev/fd/2
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
